scene.setBackgroundImage(assets.image`myImage`)
let lion = sprites.create(assets.image`myImage0`, SpriteKind.Player)
lion.setPosition(10, 90)
scaling.scaleByPixels(lion, 15, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let rabbit = sprites.create(assets.image`myImage1`, SpriteKind.Player)
rabbit.setPosition(31, 90)
scaling.scaleByPixels(rabbit, 7, ScaleDirection.Uniformly, ScaleAnchor.Middle)
let goat = sprites.create(assets.image`myImage3`, SpriteKind.Player)
goat.setPosition(46, 90)
let owl = sprites.create(assets.image`myImage6`, SpriteKind.Player)
let eagle = sprites.create(assets.image`myImage2`, SpriteKind.Player)
eagle.setPosition(74, 33)
let snake = sprites.create(assets.image`myImage5`, SpriteKind.Player)
snake.setPosition(65, 90)
let rat = sprites.create(assets.image`myImage4`, SpriteKind.Player)
rat.setPosition(81, 90)
